/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as StoresRouteImport } from './routes/stores'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ForShoppersRouteImport } from './routes/for-shoppers'
import { Route as ForBrandsRouteImport } from './routes/for-brands'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BookDemoRouteImport } from './routes/book-demo'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResourcesSlugRouteImport } from './routes/resources.$slug'
import { Route as FeaturesSlugRouteImport } from './routes/features.$slug'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const StoresRoute = StoresRouteImport.update({
  id: '/stores',
  path: '/stores',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ForShoppersRoute = ForShoppersRouteImport.update({
  id: '/for-shoppers',
  path: '/for-shoppers',
  getParentRoute: () => rootRouteImport,
} as any)
const ForBrandsRoute = ForBrandsRouteImport.update({
  id: '/for-brands',
  path: '/for-brands',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BookDemoRoute = BookDemoRouteImport.update({
  id: '/book-demo',
  path: '/book-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesSlugRoute = ResourcesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ResourcesRoute,
} as any)
const FeaturesSlugRoute = FeaturesSlugRouteImport.update({
  id: '/features/$slug',
  path: '/features/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/book-demo': typeof BookDemoRoute
  '/contact': typeof ContactRoute
  '/discover': typeof DiscoverRoute
  '/for-brands': typeof ForBrandsRoute
  '/for-shoppers': typeof ForShoppersRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/resources': typeof ResourcesRouteWithChildren
  '/signup': typeof SignupRoute
  '/stores': typeof StoresRoute
  '/terms': typeof TermsRoute
  '/features/$slug': typeof FeaturesSlugRoute
  '/resources/$slug': typeof ResourcesSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/book-demo': typeof BookDemoRoute
  '/contact': typeof ContactRoute
  '/discover': typeof DiscoverRoute
  '/for-brands': typeof ForBrandsRoute
  '/for-shoppers': typeof ForShoppersRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/resources': typeof ResourcesRouteWithChildren
  '/signup': typeof SignupRoute
  '/stores': typeof StoresRoute
  '/terms': typeof TermsRoute
  '/features/$slug': typeof FeaturesSlugRoute
  '/resources/$slug': typeof ResourcesSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/book-demo': typeof BookDemoRoute
  '/contact': typeof ContactRoute
  '/discover': typeof DiscoverRoute
  '/for-brands': typeof ForBrandsRoute
  '/for-shoppers': typeof ForShoppersRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/resources': typeof ResourcesRouteWithChildren
  '/signup': typeof SignupRoute
  '/stores': typeof StoresRoute
  '/terms': typeof TermsRoute
  '/features/$slug': typeof FeaturesSlugRoute
  '/resources/$slug': typeof ResourcesSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/book-demo'
    | '/contact'
    | '/discover'
    | '/for-brands'
    | '/for-shoppers'
    | '/forgot-password'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/resources'
    | '/signup'
    | '/stores'
    | '/terms'
    | '/features/$slug'
    | '/resources/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/book-demo'
    | '/contact'
    | '/discover'
    | '/for-brands'
    | '/for-shoppers'
    | '/forgot-password'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/resources'
    | '/signup'
    | '/stores'
    | '/terms'
    | '/features/$slug'
    | '/resources/$slug'
  id:
    | '__root__'
    | '/'
    | '/book-demo'
    | '/contact'
    | '/discover'
    | '/for-brands'
    | '/for-shoppers'
    | '/forgot-password'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/resources'
    | '/signup'
    | '/stores'
    | '/terms'
    | '/features/$slug'
    | '/resources/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BookDemoRoute: typeof BookDemoRoute
  ContactRoute: typeof ContactRoute
  DiscoverRoute: typeof DiscoverRoute
  ForBrandsRoute: typeof ForBrandsRoute
  ForShoppersRoute: typeof ForShoppersRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  ResourcesRoute: typeof ResourcesRouteWithChildren
  SignupRoute: typeof SignupRoute
  StoresRoute: typeof StoresRoute
  TermsRoute: typeof TermsRoute
  FeaturesSlugRoute: typeof FeaturesSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stores': {
      id: '/stores'
      path: '/stores'
      fullPath: '/stores'
      preLoaderRoute: typeof StoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-shoppers': {
      id: '/for-shoppers'
      path: '/for-shoppers'
      fullPath: '/for-shoppers'
      preLoaderRoute: typeof ForShoppersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-brands': {
      id: '/for-brands'
      path: '/for-brands'
      fullPath: '/for-brands'
      preLoaderRoute: typeof ForBrandsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book-demo': {
      id: '/book-demo'
      path: '/book-demo'
      fullPath: '/book-demo'
      preLoaderRoute: typeof BookDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/$slug': {
      id: '/resources/$slug'
      path: '/$slug'
      fullPath: '/resources/$slug'
      preLoaderRoute: typeof ResourcesSlugRouteImport
      parentRoute: typeof ResourcesRoute
    }
    '/features/$slug': {
      id: '/features/$slug'
      path: '/features/$slug'
      fullPath: '/features/$slug'
      preLoaderRoute: typeof FeaturesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ResourcesRouteChildren {
  ResourcesSlugRoute: typeof ResourcesSlugRoute
}

const ResourcesRouteChildren: ResourcesRouteChildren = {
  ResourcesSlugRoute: ResourcesSlugRoute,
}

const ResourcesRouteWithChildren = ResourcesRoute._addFileChildren(
  ResourcesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BookDemoRoute: BookDemoRoute,
  ContactRoute: ContactRoute,
  DiscoverRoute: DiscoverRoute,
  ForBrandsRoute: ForBrandsRoute,
  ForShoppersRoute: ForShoppersRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  ResourcesRoute: ResourcesRouteWithChildren,
  SignupRoute: SignupRoute,
  StoresRoute: StoresRoute,
  TermsRoute: TermsRoute,
  FeaturesSlugRoute: FeaturesSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
